import { getApp, getApps, initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { collection, doc, getDoc, getDocs, getFirestore, orderBy, query } from 'firebase/firestore';
import { createClient } from '@supabase/supabase-js';
import firebaseConfig from '../../firebase-applet-config.json';

type AnyRecord = Record<string, any>;
type ProgressEvent = { phase: string; message: string; counts?: Record<string, number> };
export type MigrationOptions = { firebaseEmail: string; firebasePassword: string; confirm: boolean; onProgress?: (event: ProgressEvent) => void };

type Reconciliation = { passed: boolean; checked: number; mismatches: Array<{ table: string; id: string; field: string; source: unknown; destination: unknown }> };

function cleanTicker(value: unknown): string { return String(value || '').trim().toUpperCase().replace(/^EGX:/, '').replace(/\.CA$/, ''); }
function dateOnly(value: unknown): string { const text = String(value || ''); if (/^\d{4}-\d{2}-\d{2}/.test(text)) return text.slice(0, 10); const parsed = new Date(text); if (Number.isNaN(parsed.getTime())) throw new Error(`Invalid date: ${text}`); return parsed.toISOString().slice(0, 10); }
function nullableNumber(value: unknown): number | null { if (value === undefined || value === null || value === '') return null; const n = Number(value); return Number.isFinite(n) ? n : null; }
function numberOrZero(value: unknown): number { return nullableNumber(value) ?? 0; }
function getSupabase() { const url = process.env.SUPABASE_URL || 'https://jhubsrbfiqjxdgngnwaq.supabase.co'; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!key) throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured on the server.'); return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); }
async function upsert(table: string, rows: AnyRecord[], conflict: string) { const supabase = getSupabase(); for (let offset = 0; offset < rows.length; offset += 500) { const chunk = rows.slice(offset, offset + 500); const { error } = await supabase.from(table).upsert(chunk, { onConflict: conflict }); if (error) throw new Error(`${table} upsert failed: ${error.message}`); } }
function progress(options: MigrationOptions, event: ProgressEvent) { options.onProgress?.(event); console.log(`[migration] ${event.phase}: ${event.message}`); }
function sameNumber(a: unknown, b: unknown, tolerance = 0.000001): boolean { const na = nullableNumber(a); const nb = nullableNumber(b); if (na === null || nb === null) return na === nb; return Math.abs(na - nb) <= tolerance * Math.max(1, Math.abs(na), Math.abs(nb)); }
function sameDate(a: unknown, b: unknown): boolean { return dateOnly(a) === dateOnly(b); }
function sameValue(a: unknown, b: unknown, kind: 'number' | 'date' | 'text' | 'bool' = 'text'): boolean { if (kind === 'number') return sameNumber(a, b); if (kind === 'date') return sameDate(a, b); if (kind === 'bool') return Boolean(a) === Boolean(b); if (a == null && b == null) return true; return String(a ?? '') === String(b ?? ''); }

async function reconcile(supabase: ReturnType<typeof getSupabase>, portfolioId: string, source: { portfolio: AnyRecord; positions: AnyRecord[]; closedTrades: AnyRecord[]; transactions: AnyRecord[]; cashTransactions: AnyRecord[]; tickers: AnyRecord[]; historicalRows: AnyRecord[] }, options: MigrationOptions): Promise<Reconciliation> {
  const mismatches: Reconciliation['mismatches'] = [];
  let checked = 0;
  const checkRows = async (table: string, sourceRows: AnyRecord[], key: string, fields: Array<[string, string, 'number' | 'date' | 'text' | 'bool']>) => {
    const ids = sourceRows.map(r => String(r[key]));
    const { data, error } = await supabase.from(table).select('*').eq('portfolio_id', portfolioId);
    if (error) throw new Error(`Reconciliation read failed for ${table}: ${error.message}`);
    const dest = new Map((data || []).map((r: AnyRecord) => [String(r[key]), r]));
    if (dest.size !== sourceRows.length) mismatches.push({ table, id: '__COUNT__', field: 'row_count', source: sourceRows.length, destination: dest.size });
    for (const src of sourceRows) {
      const id = String(src[key]); const dst = dest.get(id); if (!dst) { mismatches.push({ table, id, field: 'missing_row', source: 'present', destination: 'missing' }); continue; }
      for (const [sourceField, destField, kind] of fields) { checked++; if (!sameValue(src[sourceField], dst[destField], kind)) mismatches.push({ table, id, field: sourceField, source: src[sourceField], destination: dst[destField] }); }
    }
    return ids;
  };

  const portfolioResult = await supabase.from('portfolios').select('*').eq('id', portfolioId).single();
  if (portfolioResult.error) throw new Error(`Reconciliation portfolio read failed: ${portfolioResult.error.message}`);
  const p = portfolioResult.data as AnyRecord;
  for (const [field, dest, kind] of [['cashBalance','cash_balance','number'], ['capitalDeposits','capital_deposits','number'], ['schemaVersion','schema_version','number']] as Array<[string,string,'number'|'date'|'text'|'bool']>) { checked++; if (!sameValue(source.portfolio[field], p[dest], kind)) mismatches.push({ table:'portfolios', id:portfolioId, field, source:source.portfolio[field], destination:p[dest] }); }

  await checkRows('tickers', source.tickers, 'ticker', [['ticker','ticker','text'],['nameEn','name_en','text'],['nameAr','name_ar','text'],['isin','isin','text'],['sector','sector','text'],['lastPrice','last_price','number'],['change','change','number'],['changePercent','change_percent','number'],['dayLow','day_low','number'],['dayHigh','day_high','number'],['yearLow','year_low','number'],['yearHigh','year_high','number'],['volume','volume','number'],['valueEgp','value_egp','number'],['rsi14','rsi14','number'],['support','support','number'],['resistance','resistance','number'],['targetPrice','target_price','number'],['stopLoss','stop_loss','number']]);
  await checkRows('positions', source.positions, 'id', [['id','id','text'],['ticker','ticker','text'],['companyName','company_name','text'],['sector','sector','text'],['shares','shares','number'],['avgBuyPrice','avg_buy_price','number'],['currentPrice','current_price','number'],['dayChange','day_change','number'],['dayChangePercent','day_change_percent','number'],['buyDate','buy_date','date'],['totalFees','total_fees','number'],['targetPrice','target_price','number'],['stopLoss','stop_loss','number']]);
  await checkRows('closed_trades', source.closedTrades, 'id', [['id','id','text'],['ticker','ticker','text'],['companyName','company_name','text'],['shares','shares','number'],['buyPrice','buy_price','number'],['sellPrice','sell_price','number'],['buyDate','buy_date','date'],['sellDate','sell_date','date'],['holdingDays','holding_days','number'],['realizedPnlEgp','realized_pnl_egp','number'],['realizedPnlPercent','realized_pnl_percent','number'],['buyFees','buy_fees','number'],['sellFees','sell_fees','number'],['totalFees','total_fees','number'],['outcome','outcome','text'],['tradeType','trade_type','text'],['tradeCycle','trade_cycle','number'],['cycleTag','cycle_tag','text']]);
  await checkRows('transactions', source.transactions, 'id', [['id','id','text'],['type','transaction_type','text'],['ticker','ticker','text'],['companyName','company_name','text'],['shares','shares','number'],['price','price','number'],['date','transaction_date','date'],['fees','fees','number'],['totalAmount','total_amount','number'],['cashFlowType','cash_flow_type','text'],['cashFlowAmount','cash_flow_amount','number'],['isDCA','is_dca','bool'],['tradeId','trade_id','text'],['tradeCycle','trade_cycle','number'],['runningShares','running_shares','number'],['grossTradeValue','gross_trade_value','number'],['netCashImpact','net_cash_impact','number'],['realizedPnlEgp','realized_pnl_egp','number'],['realizedPnlPercent','realized_pnl_percent','number'],['holdingDays','holding_days','number'],['positionId','position_id','text']]);
  await checkRows('cash_transactions', source.cashTransactions, 'id', [['id','id','text'],['transaction_type','transaction_type','text'],['amount','amount','number'],['transaction_date','transaction_date','date'],['balance_after','balance_after','number']]);

  const history = await supabase.from('price_history').select('ticker,trading_date,open,high,low,close,volume,source').in('ticker', [...new Set(source.historicalRows.map(r => r.ticker))]);
  if (history.error) throw new Error(`Reconciliation read failed for price_history: ${history.error.message}`);
  const historyMap = new Map((history.data || []).map((r: AnyRecord) => [`${r.ticker}|${r.trading_date}`, r]));
  if ((history.data || []).length !== source.historicalRows.length) mismatches.push({ table:'price_history', id:'__COUNT__', field:'row_count', source:source.historicalRows.length, destination:(history.data || []).length });
  for (const src of source.historicalRows) { checked += 8; const id = `${src.ticker}|${src.trading_date}`; const dst = historyMap.get(id); if (!dst) { mismatches.push({ table:'price_history', id, field:'missing_row', source:'present', destination:'missing' }); continue; } for (const [f,kind] of [['ticker','text'],['trading_date','date'],['open','number'],['high','number'],['low','number'],['close','number'],['volume','number'],['source','text']] as Array<[string,'number'|'date'|'text'|'bool']>) if (!sameValue(src[f], dst[f], kind)) mismatches.push({ table:'price_history', id, field:f, source:src[f], destination:dst[f] }); }

  const passed = mismatches.length === 0;
  progress(options, { phase:'reconciliation', message: passed ? `PASS: ${checked} financial/data fields reconciled with zero mismatches.` : `FAIL: ${mismatches.length} mismatches found across ${checked} checked fields.`, counts:{ checked, mismatches:mismatches.length } });
  return { passed, checked, mismatches: mismatches.slice(0, 100) };
}

export async function runFirestoreSupabaseMigration(options: MigrationOptions) {
  if (!options.confirm) throw new Error('Migration was not explicitly confirmed.');
  if (!options.firebaseEmail || !options.firebasePassword) throw new Error('Firebase email and password are required.');
  const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
  const auth = getAuth(app); const credential = await signInWithEmailAndPassword(auth, options.firebaseEmail, options.firebasePassword); const firebaseUid = credential.user.uid;
  const db = getFirestore(app, firebaseConfig.firestoreDatabaseId); const supabase = getSupabase();
  progress(options, { phase:'source', message:'Reading Firestore portfolio snapshots.' });
  const userSnapshot = await getDoc(doc(db,'portfolios',firebaseUid)); const mainSnapshot = await getDoc(doc(db,'portfolios','main_portfolio'));
  const userData = userSnapshot.exists() ? userSnapshot.data() as AnyRecord : null; const mainData = mainSnapshot.exists() ? mainSnapshot.data() as AnyRecord : null;
  if (!userData && !mainData) throw new Error('No portfolio document found in Firestore.');
  const userTime = new Date(userData?.updatedAt || 0).getTime(); const mainTime = new Date(mainData?.updatedAt || 0).getTime();
  const portfolioData = userData && mainData ? (userTime >= mainTime ? userData : mainData) : (userData || mainData)!;
  progress(options, { phase:'source', message:`Using the newer portfolio snapshot. Firebase UID: ${firebaseUid}` });
  const { data: existingPortfolio, error: existingPortfolioError } = await supabase.from('portfolios').select('id').eq('owner_key',firebaseUid).maybeSingle();
  if (existingPortfolioError) throw new Error(`Could not inspect Supabase portfolio: ${existingPortfolioError.message}`);
  let portfolioId = existingPortfolio?.id as string | undefined;
  const portfolioPayload = { owner_key:firebaseUid, name:'Main Portfolio', cash_balance:numberOrZero(portfolioData.cashBalance), capital_deposits:numberOrZero(portfolioData.capitalDeposits), schema_version:Number(portfolioData.schemaVersion || 1), last_price_write_at:portfolioData.lastPriceWriteAt || null, updated_at:portfolioData.updatedAt || new Date().toISOString() };
  if (portfolioId) { const { error } = await supabase.from('portfolios').update(portfolioPayload).eq('id',portfolioId); if (error) throw new Error(`Could not update Supabase portfolio: ${error.message}`); } else { const { data,error } = await supabase.from('portfolios').insert(portfolioPayload).select('id').single(); if (error) throw new Error(`Could not create Supabase portfolio: ${error.message}`); portfolioId=data.id; }
  const positions = Array.isArray(portfolioData.positions) ? portfolioData.positions : []; const closedTrades = Array.isArray(portfolioData.closedTrades) ? portfolioData.closedTrades : []; const transactions = Array.isArray(portfolioData.transactions) ? portfolioData.transactions : []; const tickers = Array.isArray(portfolioData.tickers) ? portfolioData.tickers : [];
  const tickerMap = new Map<string,AnyRecord>(); for (const raw of tickers) { const ticker=cleanTicker(raw.ticker); if(ticker)tickerMap.set(ticker,raw); } for(const raw of [...positions,...transactions,...closedTrades]) { const ticker=cleanTicker(raw.ticker); if(ticker&&!tickerMap.has(ticker)) tickerMap.set(ticker,{ticker,nameEn:raw.companyName||'',nameAr:'',isin:'',sector:raw.sector||'Other'}); }
  const tickerRows=[...tickerMap.entries()].map(([ticker,raw])=>({ticker,name_en:String(raw.nameEn||raw.companyName||''),name_ar:String(raw.nameAr||''),isin:String(raw.isin||''),sector:String(raw.sector||'Other'),last_price:numberOrZero(raw.lastPrice),change:numberOrZero(raw.change),change_percent:numberOrZero(raw.changePercent),day_low:numberOrZero(raw.dayLow),day_high:numberOrZero(raw.dayHigh),year_low:numberOrZero(raw.yearLow),year_high:numberOrZero(raw.yearHigh),volume:numberOrZero(raw.volume),value_egp:numberOrZero(raw.valueEgp),trend_status:String(raw.trendStatus||'Rangebound Neutral'),rsi14:numberOrZero(raw.rsi14),support:numberOrZero(raw.support),resistance:numberOrZero(raw.resistance),target_price:numberOrZero(raw.targetPrice),stop_loss:numberOrZero(raw.stopLoss),notes:raw.notes??null,last_updated:raw.lastUpdated||null,price_updated_at:raw.priceUpdatedAt||null,logo_url:raw.logoUrl||null,updated_at:new Date().toISOString()}));
  await upsert('tickers',tickerRows,'ticker'); progress(options,{phase:'tickers',message:`Migrated ${tickerRows.length} tickers.`,counts:{tickers:tickerRows.length}});
  const positionRows=positions.map((p:AnyRecord)=>({id:String(p.id),portfolio_id:portfolioId,ticker:cleanTicker(p.ticker),company_name:String(p.companyName||''),sector:String(p.sector||'Other'),shares:numberOrZero(p.shares),avg_buy_price:numberOrZero(p.avgBuyPrice),current_price:numberOrZero(p.currentPrice),day_change:nullableNumber(p.dayChange),day_change_percent:nullableNumber(p.dayChangePercent),buy_date:dateOnly(p.buyDate),total_fees:numberOrZero(p.totalFees),target_price:nullableNumber(p.targetPrice),stop_loss:nullableNumber(p.stopLoss),notes:p.notes??null,price_updated_at:p.priceUpdatedAt||null})); await upsert('positions',positionRows,'id');
  const closedTradeRows=closedTrades.map((t:AnyRecord)=>({id:String(t.id),portfolio_id:portfolioId,ticker:cleanTicker(t.ticker),company_name:String(t.companyName||''),sector:String(t.sector||'Other'),shares:numberOrZero(t.shares),buy_price:numberOrZero(t.buyPrice),sell_price:numberOrZero(t.sellPrice),buy_date:dateOnly(t.buyDate),sell_date:dateOnly(t.sellDate),holding_days:Math.max(0,Math.trunc(numberOrZero(t.holdingDays))),realized_pnl_egp:numberOrZero(t.realizedPnlEgp),realized_pnl_percent:numberOrZero(t.realizedPnlPercent),buy_fees:numberOrZero(t.buyFees),sell_fees:numberOrZero(t.sellFees),total_fees:numberOrZero(t.totalFees),outcome:String(t.outcome||'BREAKEVEN'),trade_type:String(t.tradeType||'Core'),trade_cycle:nullableNumber(t.tradeCycle),cycle_tag:t.cycleTag??null,notes:t.notes??null,buy_transaction_ids:Array.isArray(t.buyTransactionIds)?t.buyTransactionIds.map(String):[],sell_transaction_ids:Array.isArray(t.sellTransactionIds)?t.sellTransactionIds.map(String):[]})); await upsert('closed_trades',closedTradeRows,'id');
  const transactionRows=transactions.map((t:AnyRecord)=>({id:String(t.id),portfolio_id:portfolioId,transaction_type:String(t.type||'BUY'),ticker:cleanTicker(t.ticker),company_name:String(t.companyName||''),sector:String(t.sector||'Other'),shares:numberOrZero(t.shares),price:numberOrZero(t.price),transaction_date:dateOnly(t.date),executed_at:t.executedAt||null,fees:numberOrZero(t.fees),total_amount:numberOrZero(t.totalAmount),cash_flow_type:t.cashFlowType||null,cash_flow_amount:nullableNumber(t.cashFlowAmount),is_dca:Boolean(t.isDCA),notes:t.notes??null,target_price:nullableNumber(t.targetPrice),stop_loss:nullableNumber(t.stopLoss),trade_id:t.tradeId==null?(t.trade_id==null?null:String(t.trade_id)):String(t.tradeId),trade_cycle:nullableNumber(t.tradeCycle),cycle_tag:t.cycleTag??null,running_shares:nullableNumber(t.runningShares),gross_trade_value:nullableNumber(t.grossTradeValue),net_cash_impact:nullableNumber(t.netCashImpact),realized_pnl_egp:nullableNumber(t.realizedPnlEgp),realized_pnl_percent:nullableNumber(t.realizedPnlPercent),outcome:t.outcome||null,holding_days:nullableNumber(t.holdingDays),position_id:t.positionId||null})); await upsert('transactions',transactionRows,'id');
  const cashTransactions=transactions.filter((t:AnyRecord)=>['DEPOSIT','WITHDRAWAL','DIVIDEND','FEE'].includes(String(t.cashFlowType||'').toUpperCase())).map((t:AnyRecord)=>({id:String(t.id),portfolio_id:portfolioId,transaction_type:String(t.cashFlowType).toUpperCase(),amount:numberOrZero(t.cashFlowAmount??t.totalAmount),transaction_date:dateOnly(t.date),notes:t.notes??null,balance_after:nullableNumber(t.balanceAfter)})); await upsert('cash_transactions',cashTransactions,'id');
  const securityTickers=[...tickerMap.keys()].filter(t=>t!=='CASH'); let historicalRows=0; const historySourceRows:AnyRecord[]=[];
  for(const ticker of securityTickers){ const snapshot=await getDocs(query(collection(db,'historicalPrices',ticker,'daily'),orderBy('date','asc'))); const rows=snapshot.docs.map(s=>{const p=s.data() as AnyRecord; return {ticker,trading_date:dateOnly(p.date),open:nullableNumber(p.open),high:nullableNumber(p.high),low:nullableNumber(p.low),close:numberOrZero(p.close),volume:nullableNumber(p.volume),source:String(p.source||'tradingview'),retrieved_at:p.retrievedAt||null};}).filter(p=>p.close>0); historySourceRows.push(...rows); await upsert('price_history',rows,'ticker,trading_date'); historicalRows+=rows.length; progress(options,{phase:'history',message:`${ticker}: ${rows.length} historical price rows.`,counts:{historicalPrices:historicalRows}}); }
  const reconciliation=await reconcile(supabase,portfolioId,{portfolio:portfolioData,positions,closedTrades,transactions,cashTransactions,tickers:tickerRows.map(r=>({ticker:r.ticker,nameEn:r.name_en,nameAr:r.name_ar,isin:r.isin,sector:r.sector,lastPrice:r.last_price,change:r.change,changePercent:r.change_percent,dayLow:r.day_low,dayHigh:r.day_high,yearLow:r.year_low,yearHigh:r.year_high,volume:r.volume,valueEgp:r.value_egp,rsi14:r.rsi14,support:r.support,resistance:r.resistance,targetPrice:r.target_price,stopLoss:r.stop_loss})),historicalRows:historySourceRows},options);
  if(!reconciliation.passed) throw new Error(`Migration written but reconciliation FAILED with ${reconciliation.mismatches.length} mismatches. Review the reconciliation report before rerunning.`);
  const counts={tickers:tickerRows.length,positions:positionRows.length,transactions:transactionRows.length,closedTrades:closedTradeRows.length,cashTransactions:cashTransactions.length,historicalPrices:historicalRows}; progress(options,{phase:'complete',message:'Migration completed and field-level reconciliation PASSED. Firebase was read only.',counts});
  return {portfolioId,firebaseUid,counts,reconciliation};
}
